version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/wwww
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - "8000:9000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
    # networks:
    #   - poc
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
